INICIO:
CLS
PRINT ""
PRINT "  PROGRAMA QUE CALCULA EL PRESTAMO DE UNA FINANCIERA"
PRINT
INPUT " DIGITE EL MONTO DEL PRESTAMO  : ", MONTO
INPUT " DIGITE LA TASA DEL PRESTAMO   : ", TASA
INPUT " DIGITE EL TIEMPO DEL PRESTAMO : ", TIEMPO

REM CLACULO DE LOS INTERESES

INTERESES = MONTO * TASA / 100

REM CALCULO DEL TIEMPO

TIEMPOPAGO = TIEMPO * 12

REM CALCULO MONTO TOTAL                        

TOTAL = MONTO + INTERESES

REM CALCULO LAS CUAOTAS MENSUALES


CUOTAS = TOTAL / TIEMPOPAGO


REM ACUMULADO PARA EL PRSTAMO E INTERSES
                         

TP = TP + MONTO
INTE = INTE + INTERESES

PRINT "--------------------------------------------------"

PRINT
PRINT " EL INTERES ES  : ", INTERESES
PRINT
PRINT " EL TIEMPO ES   : ", TIEMPOPAGO
PRINT
PRINT " EL TOTAL A PAGAR INTERESES MAS CAPITAL: ", TOTAL
PRINT
PRINT " LOS PAGOS MENSEALES SERAN DE           : ", CUOTAS

END
















